blueprint:
  name: Paralelo Virtual - mcamtech V1.2
  description: Acende/Apaga todos os switches/lights do grupo simultaneamente
  domain: automation
  input:
    entrada_switchs:
      name: Escolha os pontos de Iluminação
      selector:
        entity:
          domain:
            - switch
            - light
          multiple: true

variables:
  entidades: !input entrada_switchs

trigger:
  - platform: state
    entity_id: !input entrada_switchs
    to:
      - "on"
      - "off"

condition:
  - condition: template
    value_template: >
      {{ expand(entidades)
         | rejectattr('state', 'eq', trigger.to_state.state)
         | list | count > 0 }}

action:
  - service: "homeassistant.turn_{{ trigger.to_state.state }}"
    target:
      entity_id: !input entrada_switchs
  - delay:
      seconds: 2

mode: single
