blueprint:
  name: Paralelo Virtual - mcamtech - V1.1
  description: Acende/Apaga todos os switches/lights do grupo simultaneamente
  domain: automation
  input:
    entrada_switchs:
      name: Escolha os pontos de Iluminação
      selector:
        entity:
          domain:
            - switch
            - light
          multiple: true

trigger:
  - platform: state
    entity_id: !input entrada_switchs
    to:
      - "on"
      - "off"

action:
  - service: "homeassistant.turn_{{ trigger.to_state.state }}"
    target:
      entity_id: !input entrada_switchs
  - delay:
      seconds: 1

mode: single
